### ISSUE TITLE
error

### ISSUE THREAD

**Issue by stibenlopez** [AuxGrep/Ahmyth-FIXED#2]
el programa no funciona, se inicio pero no me deja seleccionar el apk

**Comment by Morsmalleo** [comment]
> el programa no funciona, se inicio pero no me deja seleccionar el apk

This is a ridiculous repository, he's a liar that has taken credit for work that I did on an older version of AhMyth, go ahead and go to the official updated & maintained repo for AhMyth below

https://GitHub.com/Morsmalleo/AhMyth
